# Generated by Django 6.0.4 on 2026-08-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_amount_paid_booking_amount_refunded'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], default='paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('full', 'Full payment'), ('deposit', 'Deposit'), ('installment', 'Installment / top-up')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
