# Generated by Django 6.0.4 on 2026-08-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charged_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount actually sent to the gateway (GHS). Null when it equals `amount`.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='charged_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Rate used for this charge (charged_currency per 1 unit of currency).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Ledger amount in the BOOKING currency, e.g. 1000.00 USD', max_digits=12),
        ),
    ]
