# Generated by Django 6.0.4 on 2026-08-14 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_charged_amount_payment_charged_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base', models.CharField(max_length=3)),
                ('quote', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(help_text='Provider the rate came from.', max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['base', 'quote', '-fetched_at'], name='payments_fx_base_ee7c38_idx')],
            },
        ),
    ]
