# Generated by Django 6.0.4 on 2026-09-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_opsconfig_scheduledtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-requested_at'], 'permissions': [('process_refund', 'Can mark refunds processed / reject them')]},
        ),
    ]
