# Generated by Django 6.0.4 on 2026-09-28 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_options_and_more'),
        ('payments', '0007_alter_refund_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsconfig',
            name='checkout_fee_notice',
            field=models.CharField(blank=True, help_text="Shown at checkout before payment, e.g. 'Prices include all taxes and the Ghana tourism levy; no payment fees are added.' Leave empty to show nothing.", max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='dispute_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='dispute_status',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='payment',
            name='disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(help_text='e.g. confirmation, receipt, reminder, overdue', max_length=60)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('provider_id', models.CharField(blank=True, help_text='Resend message id', max_length=100)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
