# Generated by Django 6.0.4 on 2026-09-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_opsconfig_checkout_fee_notice_payment_dispute_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='addon_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('full', 'Full payment'), ('deposit', 'Deposit'), ('installment', 'Installment / top-up'), ('addon', 'Added experience')], default='full', max_length=20),
        ),
    ]
