# Generated by Django 6.0.4 on 2026-04-29 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TravelPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("luxury_travel", "Luxury Travel"),
                            ("nightlife", "Nightlife & Entertainment"),
                            ("cultural", "Cultural Immersion"),
                            ("culinary", "Culinary Experiences"),
                            ("fashion", "Fashion & Lifestyle"),
                            ("corporate", "Corporate & Group"),
                            ("bespoke", "Bespoke Concierge"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                            ("vip", "VIP"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "highlights",
                    models.JSONField(default=list, help_text="List of key highlights"),
                ),
                ("destination", models.CharField(max_length=200)),
                ("duration_days", models.PositiveIntegerField()),
                ("max_guests", models.PositiveIntegerField(default=10)),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_featured", "price_per_person"],
            },
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day",
                    models.PositiveIntegerField(
                        help_text="Day number in the trip, e.g. 1, 2, 3"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 'Arrival & Welcome Dinner'", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full narrative of the day's experience"
                    ),
                ),
                (
                    "activities",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of activities, e.g. ['Airport pickup', 'Hotel check-in']",
                    ),
                ),
                (
                    "meals_included",
                    models.JSONField(
                        default=list, help_text="e.g. ['Breakfast', 'Dinner']"
                    ),
                ),
                (
                    "accommodation",
                    models.CharField(
                        blank=True,
                        help_text="Hotel or lodge name for overnight stays",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City or area for this day, e.g. 'Accra' or 'Maasai Mara'",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional tips or special instructions for the day",
                        null=True,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to="packages.travelpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["package", "day"],
                "unique_together": {("package", "day")},
            },
        ),
    ]
