# Generated by Django 6.0.4 on 2026-04-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_packageimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelpackage",
            name="available_from",
            field=models.DateField(
                blank=True, help_text="First date this package can be booked", null=True
            ),
        ),
        migrations.AddField(
            model_name="travelpackage",
            name="available_to",
            field=models.DateField(
                blank=True, help_text="Last date this package can be booked", null=True
            ),
        ),
    ]
