# Generated by Django 6.0.4 on 2026-04-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0004_packagefaq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itinerary",
            name="accommodation",
        ),
        migrations.RemoveField(
            model_name="itinerary",
            name="location",
        ),
        migrations.RemoveField(
            model_name="itinerary",
            name="meals_included",
        ),
    ]
