# Generated by Django 6.0.4 on 2026-04-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0005_remove_itinerary_meals_accommodation_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelpackage",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Decimal latitude, e.g. 5.603717",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="travelpackage",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Decimal longitude, e.g. -0.186964",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="travelpackage",
            name="map_url",
            field=models.URLField(
                blank=True,
                help_text="Google Maps or any map embed/share URL",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="travelpackage",
            name="whats_included",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="What is included in the package, e.g. ['Beverages', 'Lunch', 'Hotel pickup']",
            ),
        ),
    ]
