# Generated by Django 6.0.4 on 2026-05-03 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0011_remove_price_solo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="travelpackage",
            options={"ordering": ["-is_featured", "price_shared"]},
        ),
        migrations.AlterField(
            model_name="travelpackage",
            name="price_private",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Private (Solo) price",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="travelpackage",
            name="price_shared",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Shared / Couples price (Best Value)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="travelpackage",
            name="price_vip",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="VIP price",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DestinationImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="destinations/images/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "is_cover",
                    models.BooleanField(
                        default=False, help_text="Mark as the hero/cover image"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="packages.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "uploaded_at"],
            },
        ),
    ]
