# Generated by Django 6.0.4 on 2026-05-03 15:40

from django.db import migrations, models


def migrate_destination_text_to_m2m(apps, schema_editor):
    TravelPackage = apps.get_model("packages", "TravelPackage")
    Destination = apps.get_model("packages", "Destination")
    db_alias = schema_editor.connection.alias

    for package in TravelPackage.objects.using(db_alias).all():
        raw_destination = (package.destination or "").strip()
        if not raw_destination:
            continue

        destination_names = [name.strip() for name in raw_destination.split(",") if name.strip()]
        for destination_name in destination_names:
            destination, _ = Destination.objects.using(db_alias).get_or_create(
                name=destination_name,
                defaults={"description": f"Auto-created destination for {destination_name}."},
            )
            package.destinations.add(destination)


def migrate_destination_m2m_to_text(apps, schema_editor):
    TravelPackage = apps.get_model("packages", "TravelPackage")
    db_alias = schema_editor.connection.alias

    for package in TravelPackage.objects.using(db_alias).all():
        destination_names = list(package.destinations.values_list("name", flat=True))
        package.destination = ", ".join(destination_names)
        package.save(update_fields=["destination"])


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0012_destination_alter_travelpackage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelpackage",
            name="destinations",
            field=models.ManyToManyField(
                blank=True, related_name="packages", to="packages.destination"
            ),
        ),
        migrations.RunPython(
            migrate_destination_text_to_m2m,
            reverse_code=migrate_destination_m2m_to_text,
        ),
        migrations.RemoveField(
            model_name="travelpackage",
            name="destination",
        ),
    ]
