# Generated by Django 6.0.4 on 2026-05-03 16:21

from django.db import migrations, models


def move_package_location_to_destinations(apps, schema_editor):
    TravelPackage = apps.get_model("packages", "TravelPackage")
    db_alias = schema_editor.connection.alias

    for package in TravelPackage.objects.using(db_alias).prefetch_related("destinations"):
        has_location = any(
            [
                package.map_url,
                package.latitude is not None,
                package.longitude is not None,
            ]
        )
        if not has_location:
            continue

        for destination in package.destinations.all():
            changed = False
            if not destination.map_url and package.map_url:
                destination.map_url = package.map_url
                changed = True
            if destination.latitude is None and package.latitude is not None:
                destination.latitude = package.latitude
                changed = True
            if destination.longitude is None and package.longitude is not None:
                destination.longitude = package.longitude
                changed = True
            if changed:
                destination.save(update_fields=["map_url", "latitude", "longitude"])


def move_destination_location_to_package(apps, schema_editor):
    TravelPackage = apps.get_model("packages", "TravelPackage")
    db_alias = schema_editor.connection.alias

    for package in TravelPackage.objects.using(db_alias).prefetch_related("destinations"):
        destination = package.destinations.filter(
            models.Q(map_url__isnull=False)
            | models.Q(latitude__isnull=False)
            | models.Q(longitude__isnull=False)
        ).first()
        if not destination:
            continue

        package.map_url = destination.map_url
        package.latitude = destination.latitude
        package.longitude = destination.longitude
        package.save(update_fields=["map_url", "latitude", "longitude"])


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0013_remove_travelpackage_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Decimal latitude, e.g. 5.603717",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Decimal longitude, e.g. -0.186964",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="map_url",
            field=models.URLField(
                blank=True,
                help_text="Google Maps or any map embed/share URL",
                max_length=500,
                null=True,
            ),
        ),
        migrations.RunPython(
            move_package_location_to_destinations,
            reverse_code=move_destination_location_to_package,
        ),
        migrations.RemoveField(
            model_name="travelpackage",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="travelpackage",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="travelpackage",
            name="map_url",
        ),
    ]
