# Generated by Django 6.0.4 on 2026-08-14 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_remove_travelpackage_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelpackage',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='allow_installments',
            field=models.BooleanField(default=False, help_text='Allow customers to secure a booking with a deposit and pay the balance later.'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='deposit_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum deposit (in package currency) that confirms an installment booking.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='early_bird_deadline',
            field=models.DateTimeField(blank=True, help_text='Early-bird option prices apply to bookings created before this moment.', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='final_payment_deadline',
            field=models.DateField(blank=True, help_text='Installment balances must be fully paid by this date. Editing this applies to ALL bookings without a per-booking override.', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='refund_tiers',
            field=models.JSONField(blank=True, default=list, help_text='Refund tiers, e.g. [{"min_days": 60, "percent": 90}, {"min_days": 30, "percent": 60}, {"min_days": 14, "percent": 40}, {"min_days": 0, "percent": 0}]'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='visa_addon_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='visa_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Visa-on-arrival fee per guest, in package currency.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='visa_info',
            field=models.TextField(blank=True, help_text='Guidance shown to guests about the visa process.', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='whats_excluded',
            field=models.JSONField(blank=True, default=list, help_text="What is NOT included, e.g. ['International flights', 'Travel insurance']"),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='available_from',
            field=models.DateField(blank=True, help_text='Tour start date (first bookable date for legacy packages)', null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='available_to',
            field=models.DateField(blank=True, help_text='Tour end date (last bookable date for legacy packages)', null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='price_shared',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shared / Couples price (Best Value). Leave empty for option-based packages.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PackageOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(help_text="e.g. 'Four Points by Sheraton'", max_length=200)),
                ('star_rating', models.PositiveSmallIntegerField(default=4, help_text='Hotel star rating, e.g. 4 or 5')),
                ('hotel_image', models.ImageField(blank=True, null=True, upload_to='packages/hotels/')),
                ('occupancy', models.CharField(choices=[('single', 'Single Occupancy'), ('double', 'Couple / Double Occupancy')], max_length=10)),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Standard price per person, in the package currency.', max_digits=12)),
                ('early_bird_price_per_person', models.DecimalField(blank=True, decimal_places=2, help_text="Discounted per-person price while the package's early-bird deadline has not passed.", max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='packages.travelpackage')),
            ],
            options={
                'ordering': ['order', 'hotel_name', 'occupancy'],
                'constraints': [models.UniqueConstraint(fields=('package', 'hotel_name', 'occupancy'), name='unique_option_per_hotel_occupancy')],
            },
        ),
    ]
