# Generated by Django 6.0.4 on 2026-08-14 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_alter_travelpackage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_updates', to='packages.travelpackage')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
