# Generated by Django 6.0.4 on 2026-08-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_tripupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='charge_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='GHS per 1 unit of the package currency (e.g. 15.5000 for USD→GHS). Required for non-GHS packages. Applied at charge time; update as the market moves.', max_digits=12, null=True),
        ),
    ]
