# Generated by Django 6.0.4 on 2026-08-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_travelpackage_charge_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='fx_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percent added on top of the live market rate to absorb volatility between charge and settlement (e.g. 1.50). Ignored in manual mode.', max_digits=5),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='fx_mode',
            field=models.CharField(choices=[('live', 'Live market rate (+ margin)'), ('manual', 'Manual rate only')], default='live', help_text='Live: fetch the current market rate automatically (manual rate is the emergency fallback). Manual: always use the rate below.', max_length=10),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='charge_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='GHS per 1 unit of the package currency (e.g. 15.5000 for USD→GHS). In live mode this is only the fallback when the rate feed is down.', max_digits=12, null=True),
        ),
    ]
