# Generated by Django 6.0.4 on 2026-08-14 20:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_travelpackage_fx_margin_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='fx_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Percent added on top of the live market rate to absorb volatility between charge and settlement. Defaults to 1.50. Ignored in manual mode.', max_digits=5),
        ),
    ]
