# Generated by Django 6.0.4 on 2026-08-18 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_alter_travelpackage_fx_margin_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='is_day_tour',
            field=models.BooleanField(default=False, help_text='Flat per-person single-day tour with scheduled departure dates.'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='price_usd_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Optional ~USD figure shown alongside the GHS price (display only, never charged). e.g. 65 to show 'GHS 750 / ~$65'.", max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='TourDeparture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The Saturday (or any day) this tour runs.')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum guests for this departure. Leave blank for unlimited.', null=True)),
                ('seats_taken', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, help_text="Optional label, e.g. 'Limited spots' or 'Holiday special'.", max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='packages.travelpackage')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('package', 'date'), name='unique_departure_per_package_date')],
            },
        ),
    ]
