# Generated by Django 6.0.4 on 2026-08-18 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_travelpackage_is_day_tour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, help_text='Upload an MP4/WebM. Leave blank if using an external URL instead.', null=True, upload_to='packages/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Optional external video URL (YouTube/Vimeo) — used when no file is uploaded.', null=True)),
                ('poster', models.ImageField(blank=True, help_text='Optional thumbnail shown before the video plays.', null=True, upload_to='packages/video-posters/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='packages.travelpackage')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
