# Generated by Django 6.0.4 on 2026-08-29 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0021_packagevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='base_price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Mandatory Core Tour price per person — used only by the 'core_plus_addons' pricing model (e.g. 878.00).", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='pricing_model',
            field=models.CharField(choices=[('option_based', 'Option-based (hotel × occupancy)'), ('flat', 'Flat per-person (day tour / legacy)'), ('core_plus_addons', 'Core tour + optional add-ons')], default='flat', help_text='option_based = priced by hotel option; flat = price_shared; core_plus_addons = mandatory base + configurable add-ons + bundle discounts.', max_length=20),
        ),
        migrations.CreateModel(
            name='PackageAddonGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Accra Accommodation'", max_length=120)),
                ('selection', models.CharField(choices=[('single', 'Pick one (mutually exclusive)'), ('multi', 'Pick any')], default='single', max_length=10)),
                ('required', models.BooleanField(default=False, help_text="Must the customer choose one? Leave off for optional groups (include a $0 'No Hotel' default add-on so a null choice stays valid).")),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_groups', to='packages.travelpackage')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text="Stable machine code, e.g. 'hotel_mid', 'enzo_vip'.")),
                ('name', models.CharField(help_text='Customer-facing label.', max_length=200)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='In the package currency.', max_digits=12)),
                ('unit', models.CharField(choices=[('per_person', 'Per person (× guests)'), ('per_booking', 'Per booking (flat)')], default='per_person', max_length=12)),
                ('is_default', models.BooleanField(default=False, help_text="Pre-selected in its group (e.g. a $0 'No Hotel').")),
                ('refundable', models.BooleanField(default=True, help_text='Untick for non-refundable components (excluded from refunds).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='packages.travelpackage')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='packages.packageaddongroup')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageDiscountRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Core + Mid-Tier Hotel + all extras'", max_length=200)),
                ('percent', models.DecimalField(decimal_places=2, help_text='e.g. 10.00 for 10%.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='packages.travelpackage')),
                ('required_addons', models.ManyToManyField(help_text='ALL of these must be in the cart for the rule to qualify.', related_name='discount_rules', to='packages.packageaddon')),
            ],
            options={
                'ordering': ['-percent'],
            },
        ),
        migrations.AddConstraint(
            model_name='packageaddon',
            constraint=models.UniqueConstraint(fields=('package', 'code'), name='unique_addon_code_per_package'),
        ),
    ]
