# Generated by Django 6.0.4 on 2026-09-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0023_backfill_pricing_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='min_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum planning group for the tour to run (display only, e.g. 30). Leave empty to hide.', null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='max_guests',
            field=models.PositiveIntegerField(default=10, help_text='Most guests a single booking can hold.'),
        ),
    ]
