# Generated by Django 6.0.4 on 2026-09-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0024_travelpackage_min_group_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='deposit_unit',
            field=models.CharField(choices=[('per_booking', 'Per booking (one deposit, whatever the guest count)'), ('per_traveller', 'Per traveller (× guests, each capped at their share)')], default='per_booking', help_text="How the minimum deposit scales with guests. Per traveller charges the minimum for each guest, capped at that guest's share of the total (so a $878 guest pays $878, never the $1,000 minimum).", max_length=14),
        ),
    ]
