# Generated by Django 6.0.4 on 2026-09-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0025_travelpackage_deposit_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Total guests this tour can take across all bookings. Checkout refuses once reached. Leave empty for unlimited. (Day tours use per-departure seats.)', null=True),
        ),
    ]
