# Generated by Django 6.0.4 on 2026-04-29 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("travel_tips", "Travel Tips"),
                            ("destination", "Destination Guides"),
                            ("culture", "Culture & Lifestyle"),
                            ("food", "Food & Drink"),
                            ("luxury", "Luxury Travel"),
                            ("news", "News & Updates"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short summary shown on listing cards", max_length=500
                    ),
                ),
                ("body", models.TextField(help_text="Full blog content")),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="List of tag strings, e.g. ['accra', 'safari']",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="blog/images/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "is_cover",
                    models.BooleanField(
                        default=False, help_text="Mark as the hero/cover image"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "uploaded_at"],
            },
        ),
    ]
