# Generated by Django 6.0.4 on 2026-05-02 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingBlog",
            fields=[],
            options={
                "verbose_name": "Blog Pending Approval",
                "verbose_name_plural": "Blog Approvals",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("blog.blog",),
        ),
        migrations.AddField(
            model_name="blog",
            name="author_first_name",
            field=models.CharField(
                blank=True,
                help_text="First name of the person who published this post",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="author_last_name",
            field=models.CharField(
                blank=True,
                help_text="Last name of the person who published this post",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
