# Generated by Django 6.0.4 on 2026-05-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_add_author_name_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("travel_guides", "Travel Guides"),
                    ("cultural_experiences", "Cultural Experiences"),
                    ("safari_wildlife", "Safari & Wildlife"),
                    ("luxury", "Luxury Travel"),
                    ("food", "Food & Cuisine"),
                    ("diaspora", "Diaspora Stories"),
                ],
                max_length=30,
            ),
        ),
    ]
