# Generated by Django 6.0.4 on 2026-05-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="review",
            name="is_verified",
        ),
    ]
