"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _
import os
import sys
from dotenv import load_dotenv

from config.unfold_theme import AURORA_GREY, GOLD


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env.prod in production, .env in development
_env_file = ".env.prod" if os.environ.get("DJANGO_ENV") == "production" else ".env"
load_dotenv(BASE_DIR / _env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-th(=^b337c-1pste3n9#%!&x9!d0-vh+$x#z%5om6^@!t2j^45",  # dev fallback only
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() not in ("false", "0", "no")

# In production set ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com in .env.prod
_allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "azuratravelsbackend.cc,azuratravels.live,localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]

# In production set CORS_ALLOWED_ORIGINS=https://yourdomain.com in .env.prod
_cors_env = os.environ.get("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000,https://azuratravelsbackend.cc,https://azuratravels.live,https://www.azuratravels.live")
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_env.split(",") if o.strip()]
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins (Required for Django 4.0+)
_csrf_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000,https://azuratravelsbackend.cc,https://azuratravels.live,https://www.azuratravels.live")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_env.split(",") if o.strip()]

# Application definition

INSTALLED_APPS = [
    # unfold must come before django.contrib.admin
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party
    'django_filters',
    # local
    "accounts",
    "newsletter.apps.NewsletterConfig",
    "packages",
    "bookings",
    "payments",
    "reviews",
    "blog",
    'rest_framework',
    'drf_yasg',
    "corsheaders",
]

UNFOLD = {
    "SITE_TITLE": "Travel & Tour",
    "DASHBOARD_CALLBACK": "config.dashboard.dashboard_callback",
    "SITE_HEADER": "Travel & Tour Admin",
    "SITE_SUBHEADER": "Management Portal",
    "SITE_URL": "/",
    "SITE_SYMBOL": "travel_explore",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "BORDER_RADIUS": "8px",
    # Brand logo shared with the customer frontend (travelfrontend/assets/logo)
    "SITE_LOGO": {
        "light": lambda request: static("admin/img/logo.png"),
        "dark": lambda request: static("admin/img/logodark.png"),
    },
    "LOGIN": {
        "image": lambda request: static("admin/img/login-hero.jpg"),
    },
    "STYLES": [
        lambda request: static("admin/admin-aurora.css"),
    ],
    "SCRIPTS": [
        lambda request: static("admin/admin-aurora.js"),
    ],
    "COLORS": {
        # Neutral surfaces/borders/text derive from the Aurora grey scale;
        # brand gold stays the primary accent. Values must be full CSS colors
        # (Unfold emits them verbatim into --color-* custom properties).
        "base": AURORA_GREY,
        "primary": GOLD,
        "font": {
            "subtle-light": "var(--color-base-400)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-800)",
            "important-dark": "var(--color-base-100)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Overview"),
                "separator": False,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": "/admin/",
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": _("Users & Auth"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": "/admin/accounts/user/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Newsletter"),
                        "icon": "mail",
                        "link": "/admin/newsletter/newslettersubscriber/",
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": _("Packages"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Destinations"),
                        "icon": "place",
                        "link": "/admin/packages/destination/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Travel Packages"),
                        "icon": "luggage",
                        "link": "/admin/packages/travelpackage/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Trip Updates"),
                        "icon": "campaign",
                        "link": "/admin/packages/tripupdate/",
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": _("Bookings & Payments"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Bookings"),
                        "icon": "book_online",
                        "link": "/admin/bookings/booking/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Payments"),
                        "icon": "payments",
                        "link": "/admin/payments/payment/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Refunds"),
                        "icon": "currency_exchange",
                        "link": "/admin/payments/refund/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Exchange Rates"),
                        "icon": "trending_up",
                        "link": "/admin/payments/fxrate/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Scheduled Tasks"),
                        "icon": "schedule",
                        "link": "/admin/payments/scheduledtask/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Operational Settings"),
                        "icon": "settings",
                        "link": "/admin/payments/opsconfig/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Policy Documents"),
                        "icon": "gavel",
                        "link": "/admin/bookings/policydocument/",
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": _("Reviews"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Reviews"),
                        "icon": "star",
                        "link": "/admin/reviews/review/",
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": _("Blog"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Blog Posts"),
                        "icon": "article",
                        "link": "/admin/blog/blog/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Blog Approvals"),
                        "icon": "rate_review",
                        "link": "/admin/blog/pendingblog/",
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
        ],
    },
}




REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.StandardPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_RATES': {
        # Scoped throttles on the payment surface: initialize/verify are
        # human-triggered; status is a poll target and gets more headroom.
        'payments': '30/min',
        'payment-status': '120/min',
        'booking-status': '60/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise must come directly after SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # In-app scheduler (FX refresh, payment reminders) — replaces host crontab.
    "payments.autotasks.AutoTaskMiddleware",
]

# The in-app scheduler never runs inside the test suite (tasks reach the
# network); management commands can still be invoked explicitly in tests.
AUTOTASKS_ENABLED = "test" not in sys.argv

# Trust the X-Forwarded-Proto header from the proxy (Nginx)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# In production set DATABASE_URL=postgres://user:pass@db:5432/dbname in .env.prod
# In development SQLite is used as a zero-config fallback.

_db_url = os.environ.get("DATABASE_URL", "")

if _db_url.startswith("postgres"):
    import urllib.parse as _urlparse
    _parsed = _urlparse.urlparse(_db_url)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _parsed.path.lstrip("/"),
            "USER": _parsed.username,
            "PASSWORD": _parsed.password,
            "HOST": _parsed.hostname,
            "PORT": _parsed.port or 5432,
            "CONN_MAX_AGE": 60,  # persistent connections
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# Project-level static assets (admin theme CSS lives here)
STATICFILES_DIRS = [BASE_DIR / "static"]
# collectstatic writes here; Nginx/WhiteNoise serves from here
STATIC_ROOT = BASE_DIR / "staticfiles"
# WhiteNoise: serve compressed, cache-busted static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

# ── Frontend ─────────────────────────────────────────────────────────────────
FRONTEND_URL = os.environ.get("FRONTEND_URL", "https://azuratravels.live")

# ── Bookings ─────────────────────────────────────────────────────────────────
# Unpaid option-based bookings expire this many hours after creation (lazy —
# enforced at payment-initialize, no cron required). Also bounds how long a
# locked-in early-bird price can sit unpaid.
PENDING_BOOKING_TTL_HOURS = int(os.environ.get("PENDING_BOOKING_TTL_HOURS", "24"))

# ── FX (live exchange rates for GHS gateway charges) ─────────────────────────
# How long a fetched market rate is reused before refreshing (seconds).
FX_CACHE_SECONDS = int(os.environ.get("FX_CACHE_SECONDS", "3600"))
# How old a stored rate may be and still serve as a fallback when the
# provider is unreachable (hours). Older than this -> manual rate or refuse.
FX_MAX_STALENESS_HOURS = int(os.environ.get("FX_MAX_STALENESS_HOURS", "24"))
# Reject a fetched rate deviating more than this % from the last stored rate
# (guards against corrupted/hijacked feeds ever setting prices).
FX_SANITY_MAX_DEVIATION_PERCENT = int(os.environ.get("FX_SANITY_MAX_DEVIATION_PERCENT", "20"))
# Absolute plausibility band per pair — protects even the FIRST fetch on a
# fresh database (the relative check above needs history). A rate outside the
# band is rejected no matter what any provider claims. Review yearly.
FX_HARD_BOUNDS = {
    "USD:GHS": ("5", "60"),
}
# Email that receives critical payment/FX alerts (empty = log only).
ADMIN_ALERT_EMAIL = os.environ.get("ADMIN_ALERT_EMAIL", "")

# ── Paystack ─────────────────────────────────────────────────────────────────
# Set PAYSTACK_SECRET_KEY in your .env file or shell environment.
# Test key: sk_test_xxxx  /  Live key: sk_live_xxxx
PAYSTACK_SECRET_KEY = os.environ.get("PAYSTACK_SECRET_KEY", "")
PAYSTACK_BASE_URL = "https://api.paystack.co"

# ── Resend ────────────────────────────────────────────────────────────────────
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
RESEND_FROM_EMAIL = os.environ.get("RESEND_FROM_EMAIL", "Azura Travels <bookings@azuratravels.live>")
