# Generated by Django 6.0.4 on 2026-04-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_cart_cartitem_cart_cart_owner_xor_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="cart_owner_xor",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
