# Generated by Django 6.0.4 on 2026-08-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_cart_cart_owner_xor_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of successful payments. Cached from the payment ledger.', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of processed refunds. Cached from the refund ledger.', max_digits=12),
        ),
    ]
