# Generated by Django 6.0.4 on 2026-08-14 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_backfill_amount_paid'),
        ('packages', '0015_alter_travelpackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addons',
            field=models.JSONField(blank=True, default=list, help_text='Add-on line items, e.g. [{"code": "visa", "name": "Visa on Arrival", "unit_price": "150.00", "quantity": 2, "refundable": false}]'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('customer', 'Customer requested'), ('expired', 'Pending booking expired unpaid'), ('overdue_forfeit', 'Payment deadline missed'), ('admin', 'Cancelled by admin')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deposit that confirms this booking (installment plan only).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='early_bird_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='early_bird_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total early-bird saving locked in at booking time.', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='packages.packageoption'),
        ),
        migrations.AddField(
            model_name='booking',
            name='option_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='What was bought: hotel name, star rating, occupancy, per-person price.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_deadline_override',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_plan',
            field=models.CharField(choices=[('full', 'Full Payment'), ('installment', 'Installment')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_tiers_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Refund policy tiers the customer accepted at booking time.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminders_sent',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('terms', 'Booking Terms & Conditions'), ('installment', 'Installment Payment Policy'), ('refund', 'Cancellation & Refund Policy'), ('privacy', 'Privacy Policy')], max_length=20)),
                ('version', models.CharField(help_text="e.g. '1.0'", max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_current', models.BooleanField(default=False, help_text='The version shown to customers and required at checkout.')),
                ('published_at', models.DateTimeField(blank=True, help_text='Set when published. Published documents can no longer be edited.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['type', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('type', 'version'), name='unique_policy_version')],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acceptances', to='bookings.booking')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='bookings.policydocument')),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'document'), name='one_acceptance_per_document')],
            },
        ),
    ]
