# Generated by Django 6.0.4 on 2026-08-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_addons_booking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bundle discount applied to the subtotal (already reflected in total_amount).', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_note',
            field=models.CharField(blank=True, help_text="Which discount rule was applied, e.g. 'Core + Mid-Tier Hotel + all extras (10%)'.", max_length=200, null=True),
        ),
    ]
