# Generated by Django 6.0.4 on 2026-09-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_discount_amount_booking_discount_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocument',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Untick for optional consents (e.g. photography/media): they are offered unticked at checkout and never block a booking.'),
        ),
        migrations.AlterField(
            model_name='policydocument',
            name='type',
            field=models.CharField(choices=[('terms', 'Booking Terms & Conditions'), ('installment', 'Installment Payment Policy'), ('refund', 'Cancellation & Refund Policy'), ('privacy', 'Privacy Policy'), ('media', 'Photography & Media Consent')], max_length=20),
        ),
    ]
