# Generated by Django 6.0.4 on 2026-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_overdue_notice_sent_at_cancellationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'permissions': [('view_special_requests', "Can view guests' special requests (may contain health data)"), ('mark_arrived', 'Can mark a guest as arrived / tour started'), ('extend_deadline', "Can extend a booking's payment deadline"), ('cancel_booking', 'Can cancel a booking (guest bands apply)'), ('cancel_as_organizer', 'Can cancel as organizer (full refund)')]},
        ),
        migrations.AlterModelOptions(
            name='cancellationrequest',
            options={'ordering': ['-requested_at'], 'permissions': [('resolve_cancellation', 'Can approve or reject cancellation requests')]},
        ),
        migrations.AddField(
            model_name='booking',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='Set by staff when the guest arrives / the tour starts for them.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_deadline_override_reason',
            field=models.CharField(blank=True, help_text='Why the deadline was extended (policy: every extension is recorded in writing).', max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('customer', 'Customer requested'), ('expired', 'Pending booking expired unpaid'), ('overdue_forfeit', 'Payment deadline missed'), ('admin', 'Cancelled by admin'), ('organizer', 'Cancelled by Azura (organizer)')], max_length=20, null=True),
        ),
    ]
