# Generated by Django 6.0.4 on 2026-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='traveller_changes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
