# Generated by Django 6.0.4 on 2026-09-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_traveller_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addon_changes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
